### ISSUE TITLE
Chapter 2 - Seasonality code not working

### ISSUE THREAD

**Issue by Seriosso** [PacktPublishing/Learn-Algorithmic-Trading#6]
The code of Seasonality does not work properly. when we copy paste the code an error occurs. I am using the 3.9 version python. I believe the problem is in this section:

goog_monthly_return = goog_data['Adj Close'].pct_change().groupby(
    [goog_data['Adj Close'].index.year,
     goog_data['Adj Close'].index.month]).mean()

goog_montly_return_list=[]
for i in range(len(goog_monthly_return)):
    goog_montly_return_list.append\
        ({'month':goog_monthly_return.index[i][1],
          'monthly_return': goog_monthly_return[i]})

**Comment by Seriosso** [comment]
Solved:
the code should be as follow:
goog_montly_return_list=[]
for i in range(len(goog_monthly_return)):
    goog_montly_return_list.append\
        ({'month':goog_monthly_return.index[i][1],
          'monthly_return': goog_monthly_return.iloc[i]})

**Comment by Seriosso** [comment]
Check my solution above.

**Comment by gaurav-packt** [comment]
Hello,
Thank you for the resolution. With this I'm closing the issue. In case the issue persists please reopen it.
